<?php
namespace Model;

class RebelShip extends AbstractShip
{
    public function getFavoriteJedi() {

        $coolJedis = array('Yoda', 'Ben Kenobi');
        $key = array_rand($coolJedis);
        return $coolJedis['key'];

    }


    public function getType()
    {
        return 'Rebel';
    }


    public function isFunctional() {

        return true;
    }

    public function getNameAndSpecs($useShorFormat = false)
    {
        $val = parent::getNameAndSpecs($useShorFormat); // TODO: Change the autogenerated stub
        $val .= ' (Rebel)';

        return $val;
    }

    public function getJediFactor()
    {
        return rand(10, 30);
    }


}